// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Gev4Fbqj2pIuMud6ZdyLhfVTi5anSkQ',
    appId: '1:476474245368:web:30270794e14de73d813b0d',
    messagingSenderId: '476474245368',
    projectId: 'billhosthotel',
    authDomain: 'billhosthotel.firebaseapp.com',
    storageBucket: 'billhosthotel.firebasestorage.app',
    measurementId: 'G-HNG8CQM0E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_McmKhKbs2o7F0pLyLUm-kE5XNQIGhfU',
    appId: '1:476474245368:android:c3d91bed091e6bd6813b0d',
    messagingSenderId: '476474245368',
    projectId: 'billhosthotel',
    storageBucket: 'billhosthotel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLpYIQMTD6rivst_8IQtOvIkxfG0tk3Xk',
    appId: '1:476474245368:ios:6f16facb64204974813b0d',
    messagingSenderId: '476474245368',
    projectId: 'billhosthotel',
    storageBucket: 'billhosthotel.firebasestorage.app',
    iosBundleId: 'com.example.billhosts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLpYIQMTD6rivst_8IQtOvIkxfG0tk3Xk',
    appId: '1:476474245368:ios:6f16facb64204974813b0d',
    messagingSenderId: '476474245368',
    projectId: 'billhosthotel',
    storageBucket: 'billhosthotel.firebasestorage.app',
    iosBundleId: 'com.example.billhosts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9Gev4Fbqj2pIuMud6ZdyLhfVTi5anSkQ',
    appId: '1:476474245368:web:6b375d798cff323e813b0d',
    messagingSenderId: '476474245368',
    projectId: 'billhosthotel',
    authDomain: 'billhosthotel.firebaseapp.com',
    storageBucket: 'billhosthotel.firebasestorage.app',
    measurementId: 'G-0KKPW09V49',
  );

}