// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdnQmQ0L21MZ-mJ_YGdaQdpLdqTNhvq_g',
    appId: '1:237675195585:web:950d21f8a83f44ffec7840',
    messagingSenderId: '237675195585',
    projectId: 'billhostkds',
    authDomain: 'billhostkds.firebaseapp.com',
    storageBucket: 'billhostkds.firebasestorage.app',
    measurementId: 'G-TXM6FLX0S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9GIDQrq03ZPRbKxvQaCHoNbkIH5ygk78',
    appId: '1:237675195585:android:4166d3a45aefb64bec7840',
    messagingSenderId: '237675195585',
    projectId: 'billhostkds',
    storageBucket: 'billhostkds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS1EryZafusAJge9Lh-WCm4l9_WJz_wKc',
    appId: '1:237675195585:ios:c0f31a6ac1ba8e27ec7840',
    messagingSenderId: '237675195585',
    projectId: 'billhostkds',
    storageBucket: 'billhostkds.firebasestorage.app',
    iosBundleId: 'com.example.billhosts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS1EryZafusAJge9Lh-WCm4l9_WJz_wKc',
    appId: '1:237675195585:ios:c0f31a6ac1ba8e27ec7840',
    messagingSenderId: '237675195585',
    projectId: 'billhostkds',
    storageBucket: 'billhostkds.firebasestorage.app',
    iosBundleId: 'com.example.billhosts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdnQmQ0L21MZ-mJ_YGdaQdpLdqTNhvq_g',
    appId: '1:237675195585:web:c0b5c8466b0b9779ec7840',
    messagingSenderId: '237675195585',
    projectId: 'billhostkds',
    authDomain: 'billhostkds.firebaseapp.com',
    storageBucket: 'billhostkds.firebasestorage.app',
    measurementId: 'G-V2EL9QJ78D',
  );

}